options {
    # Bind runs chrooted to "/var/named/" so "/" is actually "/var/named"
    directory: "/"
};

zone "gonzalez.com.it" {
    type            master;
    file            "dns/gonzalez.com.it.hosts";
};

zone "torres.org.uk" {
    type            slave;
    masters         { 10.2.77.188; };
    file            "dns/slave/torres.org.uk.hosts"
};

zone "localhost" {
    type            master;
    file            "dns/localhost.hosts";
};

zone "127.in-addr.arpa" {
    type            master;
    file            "dns/127.in-addr.arpa.hosts";
};

zone "." {
    type            hint;
    file            "dns/named.ca";
};